### ISSUE TITLE
Test  Android-CPP

### ISSUE THREAD

**Issue by wanghuan1115** [sdkbox/sdkbox-playphone-sample#4]
playphone 需安装PLAYPHONEGames_PROD_2.1.830.apk

以下是 playphone android cpp 的测试结果

### Load

点击返回了以下结果

~~~
Got sku details: SkuDetails:{"title":"coin_package","price":"$1.00","type":"inapp","price_amount_micros":1000000,"description":"","price_currency_code":"USD","productId":"com.cocos2dx.plugintest2"}
~~~

~~~
Got sku details: SkuDetails:{"title":"coin_package2","price":"$1.00","type":"inapp","price_amount_micros":1000000,"description":"","price_currency_code":"USD","productId":"com.cocos2dx.plugintest3"}
~~~

~~~
Got sku details: SkuDetails:{"title":"remove_ads","price":"$1.00","type":"inapp","price_amount_micros":1000000,"description":"","price_currency_code":"USD","productId":"com.cocos2dx.non1"}
~~~

~~~
Got sku details: SkuDetails:{"title":"double_coin","price":"$1.00","type":"inapp","price_amount_micros":1000000,"description":"","price_currency_code":"USD","productId":"com.cocos2dx.non2"}
~~~

~~~
Playphone Request result : 0 msg : Product request successful. data :[{"id":"com.cocos2dx.non2","title":"double_coin","currencyCode":"USD","price":"$1.00","desc":"","priceValue":1},{"id":"com.cocos2dx.plugintest2","title":"coin_package","currencyCode":"USD","price":"$1.00","desc":"","priceValue":1},{"id":"com.cocos2dx.non1","title":"remove_ads","currencyCode":"USD","price":"$1.00","desc":"","priceValue":1},{"id":"com.cocos2dx.plugintest3","title":"coin_package2","currencyCode":"USD","price":"$1.00","desc":"","priceValue":1}]
~~~

### Restore

点击后输出:

~~~
NetWork reachable : true
Owned items response: 0
virtual void HelloWorld::onRestoreComplete(bool, const string&):1:
~~~

### update leaderboard random [1,100]

点击后返回:

~~~
{"response":"1"}
~~~

### fetch

点击后返回:

~~~
{"all_time":[{"rank":1,"score":100,"name":"Guest","picture":""},{"rank":2,"score":99,"name":"Guest","picture":""},{"rank":3,"score":98,"name":"Guest","picture":""},{"rank":4,"score":89,"name":"Guest","picture":""},{"rank":5,"score":86,"name":"Guest","picture":""},{"rank":6,"score":82,"name":"Guest","picture":""},{"rank":7,"score":82,"name":"Guest","picture":""},{"rank":8,"score":76,"name":"Guest","picture":""},{"rank":9,"score":68,"name":"Guest","picture":""},{"rank":10,"score":68,"name":"Guest","picture":""},{"rank":11,"score":53,"name":"Guest","picture":""},{"rank":12,"score":45,"name":"Guest","picture":""},{"rank":13,"score":28,"name":"Guest","picture":""},{"rank":14,"score":17,"name":"Guest","picture":""},{"rank":15,"score":16,"name":"Guest","picture":""},{"rank":16,"score":16,"name":"Guest","picture":""},{"rank":17,"score":5,"name":"Guest","picture":""},{"rank":18,"score":2,"name":"Guest","picture":""}],"weekly":[{"rank":1,"score":86,"name":"Guest","picture":""},{"rank":2,"score":40,"name":"Guest","picture":""}],"today":[{"rank":1,"score":86,"name":"Guest","picture":""}]}
~~~

~~~
getLeaderboard all_time: [{"picture":"","score":100,"rank":1,"name":"Guest"},{"picture":"","score":99,"rank":2,"name":"Guest"},{"picture":"","score":98,"rank":3,"name":"Guest"},{"picture":"","score":89,"rank":4,"name":"Guest"},{"picture":"","score":86,"rank":5,"name":"Guest"},{"picture":"","score":82,"rank":6,"name":"Guest"},{"picture":"","score":82,"rank":7,"name":"Guest"},{"picture":"","score":76,"rank":8,"name":"Guest"},{"picture":"","score":68,"rank":9,"name":"Guest"},{"picture":"","score":68,"rank":10,"name":"Guest"},{"picture":"","score":53,"rank":11,"name":"Guest"},{"picture":"","score":45,"rank":12,"name":"Guest"},{"picture":"","score":28,"rank":13,"name":"Guest"},{"picture":"","score":17,"rank":14,"name":"Guest"},{"picture":"","score":16,"rank":15,"name":"Guest"},{"picture":"","score":16,"rank":16,"name":"Guest"},{"picture":"","score":5,"rank":17,"name":"Guest"},{"picture":"","score":2,"rank":18,"name":"Guest"}]
~~~

~~~
getLeaderboard weekly: [{"picture":"","score":86,"rank":1,"name":"Guest"},{"picture":"","score":40,"rank":2,"name":"Guest"}]
~~~

~~~
getLeaderboard today: [{"picture":"","score":86,"rank":1,"name":"Guest"}]
~~~

~~~
MyLeaderboardListener:onComplete: {"weekly":[{"picture":"","score":86,"rank":1,"name":"Guest"},{"picture":"","score":40,"rank":2,"name":"Guest"}],"all_time":[{"picture":"","score":100,"rank":1,"name":"Guest"},{"picture":"","score":99,"rank":2,"name":"Guest"},{"picture":"","score":98,"rank":3,"name":"Guest"},{"picture":"","score":89,"rank":4,"name":"Guest"},{"picture":"","score":86,"rank":5,"name":"Guest"},{"picture":"","score":82,"rank":6,"name":"Guest"},{"picture":"","score":82,"rank":7,"name":"Guest"},{"picture":"","score":76,"rank":8,"name":"Guest"},{"picture":"","score":68,"rank":9,"name":"Guest"},{"picture":"","score":68,"rank":10,"name":"Guest"},{"picture":"","score":53,"rank":11,"name":"Guest"},{"picture":"","score":45,"rank":12,"name":"Guest"},{"picture":"","score":28,"rank":13,"name":"Guest"},{"picture":"","score":17,"rank":14,"name":"Guest"},{"picture":"","score":16,"rank":15,"name":"Guest"},{"picture":"","score":16,"rank":16,"name":"Guest"},{"picture":"","score":5,"rank":17,"name":"Guest"},{"pictu
~~~

### achievement test

点击后返回:

~~~
Secret Key: 13669982c613ba5c6a600e0029dc0837dbdf3e76
{"response":"achievement obtained already","achievements":{"3622":{"id":3622,"time":1447297758.8346}}}
~~~

### remove_ads

点击弹出购买，点击购买后提示购买成功。

### double_coin

点击弹出购买，点击购买后提示购买成功。右上角计数在不为0的情况下，double_coin完成购买后计数无变化

### coin_package2

点击弹出购买，点击购买后提示购买成功。右上角计数增加5000

### coin_package

点击弹出购买，点击购买后提示购买成功。右上角计数增加1000

**Comment by yinjimmy** [comment]
需要先安装他们的 Playphone Game Store

https://playphone.com/#

**Comment by yinjimmy** [comment]
```
E/AndroidRuntime(21562): FATAL EXCEPTION: main
E/AndroidRuntime(21562): java.lang.SecurityException: Binder invocation to an incorrect interface
E/AndroidRuntime(21562): 	at android.os.Parcel.readException(Parcel.java:1425)
E/AndroidRuntime(21562): 	at android.os.Parcel.readException(Parcel.java:1379)
E/AndroidRuntime(21562): 	at com.android.vending.playphonebilling.IInAppBillingService$Stub$Proxy.isBillingSupported(IInAppBillingService.java:208)
E/AndroidRuntime(21562): 	at com.sdkbox.plugin.playphoneutil.iap.IabHelper$1.onServiceConnected(IabHelper.java:233)
E/AndroidRuntime(21562): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1105)
E/AndroidRuntime(21562): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1122)
E/AndroidRuntime(21562): 	at android.os.Handler.handleCallback(Handler.java:615)
E/AndroidRuntime(21562): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(21562): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(21562): 	at android.app.ActivityThread.main(ActivityThread.java:4855)
E/AndroidRuntime(21562): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(21562): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(21562): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
E/AndroidRuntime(21562): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
E/AndroidRuntime(21562): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by yinjimmy** [comment]
安装 `PLAYPHONEGames_PROD_2.1.830.apk` 后解决上述崩溃问题。

正确结果
